  
version: "3"
services:
  eureka:
    build: Eureka
    ports:
      - "8761:8761"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761"]
        interval: 30s
        timeout: 10s
        retries: 5
  
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      DB_ADMIN_PASS: root
      MYSQL_DATABASE: bank-sys
    ports:
      - "3306:3306"
  
  #account:
  #  build: AccountService
  #  ports:
  #    - "8082:8082"
  #  depends_on:
  #    - mariadb
  #    - eureka
  #  links:
  #    - mariadb
  #    - eureka

  